// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test3', async function() {
    await driver.get("http://localhost:5173/read")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".nav-link:nth-child(1) > .nav11")).click()
    await driver.findElement(By.name("userId")).click()
    await driver.findElement(By.name("userId")).sendKeys("gaurav67")
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("Gaurav Anand")
    await driver.findElement(By.name("body")).click()
    await driver.findElement(By.name("body")).sendKeys("Gaurav is bad boy")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".con:nth-child(9) .btn")).click()
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("sau")
    await driver.findElement(By.css(".btn-outline-success")).click()
    await driver.findElement(By.css(".me-2")).click()
    await driver.findElement(By.css(".me-2")).sendKeys("g")
    await driver.findElement(By.css(".btn-outline-success")).click()
  })
})
